import streamlit as st
import numpy as np
import pandas as pd
from fpdf import FPDF
import math

# --- 1. SAFE IMPORT ---
try:
    import CoolProp.CoolProp as CP
    COOLPROP_AVAILABLE = True
except ImportError:
    COOLPROP_AVAILABLE = False

# ==========================================
# 2. SETUP & HELPER FUNCTIONS
# ==========================================
st.set_page_config(page_title="SGM Valve Sizing", layout="wide", page_icon="🛡️")

if 'project_log' not in st.session_state:
    st.session_state.project_log = []

# --- FLANGE RATING LIMITS (ASME B16.5 Group 1.1 Carbon Steel approx) ---
flange_limits_barg = {
    "150#": 19.6, "300#": 51.1, "600#": 102.1, "900#": 153.2, "1500#": 255.3, "2500#": 425.5
}

# --- API 526 STANDARD SIZES ---
api_526_sizes = {
    'D': ('1"', '2"'), 'E': ('1"', '2"'), 'F': ('1.5"', '2"'),
    'G': ('1.5"', '2.5"'), 'H': ('1.5"', '3"'), 'J': ('2"', '3"'),
    'K': ('3"', '4"'), 'L': ('3"', '4"'), 'M': ('4"', '6"'),
    'N': ('4"', '6"'), 'P': ('4"', '6"'), 'Q': ('6"', '8"'),
    'R': ('6"', '8"'), 'T': ('8"', '10"')
}

# --- CRITICAL PRESSURE RATIO SOLVER (For Omega Method) ---
def calculate_eta_c(omega):
    if omega <= 0: return 1.0
    eta = 0.6 
    for _ in range(50):
        try:
            term1 = eta**2
            term2 = (omega**2 - 1) * (eta**(2*omega))
            term3 = 2 * (omega**2) * math.log(eta)
            term4 = 2 * omega
            term5 = 2 * (omega**2)
            f = term1 + term2 + term3 - term4 - term5
            df = 2*eta + (omega**2 - 1)*(2*omega)*eta**(2*omega - 1) + 2*(omega**2)/eta
            if df == 0: break
            eta_new = eta - f/df
            if abs(eta_new - eta) < 0.00001: return eta_new
            eta = eta_new
        except: return 0.6
    return eta

# --- PDF GENERATOR ---
def create_datasheet(project_data, process_data, valve_data, mech_data, results_data):
    class PDF(FPDF):
        def header(self):
            try: self.image('watermark.png', x=45, y=80, w=120) 
            except: pass 
            try: self.image('logo.png', 10, 8, 33) 
            except: pass 
            self.set_y(10)
            self.set_font('Arial', 'B', 16)
            self.cell(0, 10, 'Safety Valve Datasheet', 0, 1, 'C')
            self.set_font('Arial', 'B', 12)
            self.set_text_color(0, 51, 102)
            self.cell(0, 8, 'SGM Valves and System Pvt Ltd', 0, 1, 'C')
            self.set_text_color(0, 0, 0)
            self.ln(5)
            self.set_line_width(0.5)
            self.line(10, 32, 200, 32)
            self.ln(5)

        def footer(self):
            self.set_y(-15)
            self.set_font('Arial', 'I', 8)
            self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'L')
            self.cell(0, 10, 'Generated by SGM Valves Sizing Tool', 0, 0, 'R')

    pdf = PDF()
    pdf.add_page()
    
    def print_section(title, data_dict):
        pdf.set_font("Arial", 'B', 11)
        pdf.set_fill_color(230, 230, 230)
        pdf.cell(0, 7, title, 0, 1, 'L', fill=True)
        pdf.ln(1)
        pdf.set_font("Arial", size=9)
        keys = list(data_dict.keys())
        for i in range(0, len(keys), 2):
            k1 = keys[i]
            v1 = str(data_dict[k1])
            pdf.cell(45, 6, f"{k1}:", 0, 0)
            pdf.cell(50, 6, v1, 0, 0)
            if i + 1 < len(keys):
                k2 = keys[i+1]
                v2 = str(data_dict[k2])
                pdf.cell(45, 6, f"{k2}:", 0, 0)
                pdf.cell(50, 6, v2, 0, 1)
            else: pdf.ln(6)
        pdf.ln(3)

    print_section("1. General Project Details", project_data)
    print_section("2. Process Conditions", process_data)
    print_section("3. Fluid Properties & Coefficients", valve_data)
    print_section("4. Mechanical Construction", mech_data)
    
    pdf.ln(2)
    pdf.set_fill_color(255, 255, 255)
    current_y = pdf.get_y()
    pdf.rect(10, current_y, 190, 45, 'F') 
    pdf.set_xy(10, current_y)
    pdf.set_font("Arial", 'B', 11)
    pdf.set_fill_color(230, 230, 230)
    pdf.cell(190, 7, "5. Sizing & Selection Results", 0, 1, 'L', fill=True)
    pdf.set_font("Arial", size=9)
    pdf.ln(1)
    
    keys = list(results_data.keys())
    for k in keys:
        v = str(results_data[k])
        pdf.set_x(10)
        pdf.cell(45, 6, f"{k}:", 0, 0)
        if k == "Formula Used":
            pdf.set_font("Arial", 'I', 8)
            pdf.multi_cell(140, 6, v, 0, 'L')
        else:
            pdf.cell(140, 6, v, 0, 1)
    return pdf.output(dest='S').encode('latin-1')

def get_fluid_properties(fluid_name, T_kelvin, P_kpaa, quality_x=None, service="Gas/Vapor"):
    if not COOLPROP_AVAILABLE: return {"error": "No Lib"}
    try:
        P_pa = P_kpaa * 1000
        if service == "Two-Phase" and quality_x is not None:
            rho_0 = CP.PropsSI('D', 'P', P_pa, 'Q', quality_x, fluid_name)
            v_0 = 1 / rho_0
            s_0 = CP.PropsSI('S', 'P', P_pa, 'Q', quality_x, fluid_name)
            P9_pa = 0.9 * P_pa
            rho_9 = CP.PropsSI('D', 'P', P9_pa, 'S', s_0, fluid_name)
            v_9 = 1 / rho_9
            omega = 9 * ((v_9 / v_0) - 1)
            return {"rho": rho_0, "omega": omega, "error": None}
        else:
            rho = CP.PropsSI('D', 'T', T_kelvin, 'P', P_pa, fluid_name)
            Z = CP.PropsSI('Z', 'T', T_kelvin, 'P', P_pa, fluid_name)
            mw = CP.PropsSI('M', 'T', T_kelvin, 'P', P_pa, fluid_name) * 1000
            try: cp = CP.PropsSI('Cpmass', 'T', T_kelvin, 'P', P_pa, fluid_name); cv = CP.PropsSI('Cvmass', 'T', T_kelvin, 'P', P_pa, fluid_name); k = cp/cv
            except: k = 1.01 
            try: visc = CP.PropsSI('V', 'T', T_kelvin, 'P', P_pa, fluid_name) * 1000
            except: visc = 0.0
            return {"rho": rho, "Z": Z, "k": k, "Mw": mw, "visc": visc, "error": None}
    except Exception as e: return {"error": str(e)}

# ==========================================
# 3. SIDEBAR INPUTS
# ==========================================
st.title("🛡️ SGM Valves - Sizing Pro")
st.sidebar.header("1. Project Details")
customer = st.sidebar.text_input("Customer Name", "SGM Client")
tag_no = st.sidebar.text_input("Tag Number", "PSV-1001")
desc = st.sidebar.text_input("Description", "Separator Relief")
offer_no = st.sidebar.text_input("Offer No", "25260001ABC")

st.sidebar.markdown("---")
st.sidebar.header("2. Fluid Selection")
service_type = st.sidebar.selectbox("Service Type", ["Gas/Vapor", "Liquid", "Steam", "Two-Phase"])
fluids = ["Custom (Manual Input)", "Water", "Air", "Nitrogen", "Oxygen", "CO2", "Methane", "Propane", "Ammonia"]
if not COOLPROP_AVAILABLE: fluids = ["Custom (Manual Input)"]
idx_def = 0
if service_type == "Steam" and "Water" in fluids: idx_def = fluids.index("Water")
selected_fluid = st.sidebar.selectbox("Select Fluid", fluids, index=idx_def)

st.sidebar.markdown("---")
st.sidebar.header("3. Process Conditions")
flow_units = ["kg/hr", "lb/hr", "Nm3/hr", "LPM", "m3/hr", "LPH"]
def input_w_unit(lbl, def_val, units, k):
    c1, c2 = st.sidebar.columns([2,1])
    return c1.number_input(lbl, value=def_val, key=k+"_v"), c2.selectbox("U", units, key=k+"_u")

raw_W, unit_W = input_w_unit("Flow Rate", 1000.0, flow_units, "w")
press_units = ["barg", "psig", "kPag", "kg/cm2g"]
raw_P1, unit_P1 = input_w_unit("Set Pressure", 10.0, press_units, "p1")
raw_P2, unit_P2 = input_w_unit("Back Pressure", 0.0, press_units, "p2")
raw_T1, unit_T1 = input_w_unit("Temperature", 150.0, ["°C", "°F", "K"], "t1")

# --- BELLOWS LOGIC ---
p1_bar_val = 0.0
p2_bar_val = 0.0
if unit_P1 == "barg": p1_bar_val = raw_P1
elif unit_P1 == "psig": p1_bar_val = raw_P1 * 0.0689
elif unit_P1 == "kg/cm2g": p1_bar_val = raw_P1 * 0.98
elif unit_P1 == "kPag": p1_bar_val = raw_P1 / 100

if unit_P2 == "barg": p2_bar_val = raw_P2
elif unit_P2 == "psig": p2_bar_val = raw_P2 * 0.0689
elif unit_P2 == "kg/cm2g": p2_bar_val = raw_P2 * 0.98
elif unit_P2 == "kPag": p2_bar_val = raw_P2 / 100

back_pressure_ratio = 0.0
if p1_bar_val > 0:
    back_pressure_ratio = (p2_bar_val / p1_bar_val) * 100

bellows_recommended = False
if back_pressure_ratio > 10:
    bellows_recommended = True
    st.sidebar.warning(f"⚠️ Back Pressure is {back_pressure_ratio:.1f}% (>10%). Bellows Recommended!")

input_quality = 0.0
omega_manual = 1.0
rho_inlet_manual = 1000.0

if service_type == "Two-Phase":
    st.sidebar.markdown("**Two-Phase Properties**")
    input_quality = st.sidebar.number_input("Vapor Mass Fraction (Quality x)", value=0.1, min_value=0.0, max_value=1.0)
    if selected_fluid == "Custom (Manual Input)":
        omega_manual = st.sidebar.number_input("Omega Parameter (w)", value=1.0)
        rho_inlet_manual = st.sidebar.number_input("Inlet Density (kg/m3)", value=500.0)

Ksh_manual = 1.0
if service_type == "Steam" and selected_fluid == "Custom (Manual Input)":
    st.sidebar.markdown("**Steam Correction**")
    Ksh_manual = st.sidebar.number_input("Superheat Correction Factor (Ksh)", value=1.0)

with st.sidebar.expander("4. Coefficients (Kd, Kb, Kc)"):
    def_kd = 0.975 if service_type in ["Gas/Vapor", "Steam", "Two-Phase"] else 0.65
    Kd = st.number_input("Kd (Discharge)", value=def_kd)
    Kb = st.number_input("Kb (Back Pres Factor)", value=1.0)
    Kc = st.number_input("Kc (Rupture Disc)", value=1.0)
    Kv = st.number_input("Kv (Viscosity)", value=1.0)

st.sidebar.markdown("---")
st.sidebar.header("5. Mechanical Construction")
valve_standard = st.sidebar.radio("Select Valve Standard", ["API 526 (Flanged)", "Non-API / Compact (Threaded)"])
st.sidebar.markdown("---")

c_m1, c_m2 = st.sidebar.columns(2)
body_mat = c_m1.text_input("Body Material", "WCB")
nozzle_mat = c_m2.text_input("Nozzle Material", "SS316")
c_m3, c_m4 = st.sidebar.columns(2)
disc_mat = c_m3.text_input("Disc Material", "SS316")
spring_mat = c_m4.text_input("Spring Material", "Inconel X750")

inlet_str = "N/A"
outlet_str = "N/A"
sel_inlet_sz = ""
sel_outlet_sz = ""

st.sidebar.subheader("End Connections")
if valve_standard == "API 526 (Flanged)":
    c_conn1, c_conn2 = st.sidebar.columns(2)
    inlet_rating = c_conn1.selectbox("Inlet Rating", ["150#", "300#", "600#", "900#", "1500#", "2500#"], index=1)
    
    if inlet_rating in flange_limits_barg:
        limit = flange_limits_barg[inlet_rating]
        if p1_bar_val > limit:
            st.sidebar.error(f"🚨 Set Pressure ({p1_bar_val:.1f} bar) exceeds {inlet_rating} rating limit (~{limit} bar)!")
    
    outlet_rating = c_conn2.selectbox("Outlet Rating", ["150#", "300#", "150#"], index=0)
    conn_type = st.sidebar.selectbox("Connection Type", ["RF Flange", "RTJ Flange"])
    inlet_str = f"{inlet_rating} {conn_type}"
    outlet_str = f"{outlet_rating} {conn_type}"
else:
    c_sz1, c_sz2 = st.sidebar.columns(2)
    size_options = ["1/2\"", "3/4\"", "1\"", "1 1/2\"", "2\""]
    sel_inlet_sz = c_sz1.selectbox("Inlet Size", size_options, index=0)
    sel_outlet_sz = c_sz2.selectbox("Outlet Size", size_options, index=1)
    conn_type = st.sidebar.selectbox("Connection Type", ["NPT (Male x Female)", "NPT (Female x Female)", "BSP", "Socket Weld"])
    inlet_str = f"{sel_inlet_sz} {conn_type.split(' ')[0]}"
    outlet_str = f"{sel_outlet_sz} {conn_type.split(' ')[0]}"

# --- ADDED: Centre to Face Inputs ---
st.sidebar.subheader("Dimensions")
c_dim1, c_dim2 = st.sidebar.columns(2)
c_face_inlet = c_dim1.number_input("C-to-Face Inlet (mm)", value=0)
c_face_outlet = c_dim2.number_input("C-to-Face Outlet (mm)", value=0)

lever_type = st.sidebar.selectbox("Lever Type", ["None", "Packed Lever", "Plain Lever", "Open Lever"])
bellows = st.sidebar.checkbox("Bellows Required?", value=False)

# ==========================================
# 4. CALCULATIONS
# ==========================================
atm = 101.325
def to_kpa_abs(raw, unit):
    if unit == "barg": return (raw * 100) + atm
    if unit == "psig": return (raw * 6.89476) + atm
    if unit == "kg/cm2g": return (raw * 98.0665) + atm
    if unit == "kPag": return raw + atm
    return raw

P1_abs = to_kpa_abs(raw_P1, unit_P1)
P2_abs = to_kpa_abs(raw_P2, unit_P2)
T_K = (raw_T1 + 273.15) if unit_T1 == "°C" else ((raw_T1 - 32) * 5/9 + 273.15) if unit_T1 == "°F" else raw_T1

u_Mw, u_k, u_Z, u_SG, u_visc, u_omega, u_rho = 44.0, 1.3, 0.95, 1.0, 1.0, 1.0, 10.0

if selected_fluid != "Custom (Manual Input)":
    if service_type == "Two-Phase":
        p = get_fluid_properties(selected_fluid, T_K, P1_abs, quality_x=input_quality, service="Two-Phase")
        if not p['error']:
            u_omega = p['omega']
            u_rho = p['rho']
        else: st.sidebar.error("Two-Phase Error: " + p['error'])
    else:
        p = get_fluid_properties(selected_fluid, T_K, P1_abs, service=service_type)
        if not p['error']: 
            u_Mw, u_k, u_Z, u_SG, u_visc = p['Mw'], p['k'], p['Z'], p['rho']/1000, p['visc']
            u_rho = p['rho']
        else: st.sidebar.error("Prop Error")

if selected_fluid == "Custom (Manual Input)" or (str(u_Mw)=="44.0" and selected_fluid!="CO2"):
    st.sidebar.warning("Using Manual Properties")
    if service_type == "Two-Phase":
        u_omega = omega_manual
        u_rho = rho_inlet_manual
    else:
        u_Mw = st.sidebar.number_input("MW", value=44.0)
        u_k = st.sidebar.number_input("k", value=1.3, min_value=1.01)
        u_Z = st.sidebar.number_input("Z", value=0.95)
        u_SG = st.sidebar.number_input("SG", value=1.0)

W_base = 0.0
if unit_W == "kg/hr": W_base = raw_W
elif unit_W == "lb/hr": W_base = raw_W * 0.453592
elif unit_W == "Nm3/hr": W_base = (raw_W / 22.414) * u_Mw if u_Mw > 0 else 0
elif unit_W == "LPM": W_base = (raw_W * 0.06 / 22.414) * u_Mw if u_Mw > 0 else 0
elif unit_W == "m3/hr": W_base = raw_W * 1000 * u_SG
elif unit_W == "LPH": W_base = raw_W * u_SG

# ==========================================
# 5. EXECUTION & OUTPUT
# ==========================================
st.markdown("### 📊 Sizing Dashboard")

if st.button("🚀 Calculate & Generate Datasheet"):
    try:
        if bellows_recommended and not bellows:
            st.warning("⚠️ WARNING: Back Pressure > 10% but 'Bellows Required' is NOT checked in Mechanical Construction.")

        P1_sizing = (P1_abs - atm) * 1.10 + atm 
        dP = P1_sizing - P2_abs
        A_req = 0.0
        calc_note = ""
        formula_used = ""
        
        if service_type in ["Gas/Vapor", "Steam"]:
            k_term = (u_k+1)/(u_k-1)
            C = 520 * np.sqrt(u_k * ((2/(u_k+1))**k_term))
            Kn = 1.0
            if service_type == "Steam" and P1_sizing > 10443:
                Kn = (0.276 * (P1_sizing/1000) - 1000) / (0.33 * (P1_sizing/1000) - 1061)
                calc_note = "Napier Correction (Kn) applied."
            Ksh = Ksh_manual if service_type == "Steam" and selected_fluid == "Custom (Manual Input)" else 1.0
            num = 13160 * W_base * np.sqrt((T_K * u_Z) / u_Mw)
            den = C * Kd * P1_sizing * Kb * Kc * Kn * Ksh
            A_req = num / den
            formula_used = "A = (W * sqrt(T*Z/M)) / (C * Kd * P1 * Kb * Kc)"

        elif service_type == "Liquid":
            Q_lpm = (W_base / u_SG) / 60
            if dP <= 0: st.error("Back Pres > Set Pres!"); st.stop()
            A_req = (11.78 * Q_lpm / (Kd * Kb * Kc * Kv)) * np.sqrt(u_SG / dP)
            formula_used = "A = (Q_gpm/38) / (Kd * Kw * Kc * Kv) * sqrt(G / (P1-P2))"

        elif service_type == "Two-Phase":
            eta_c = calculate_eta_c(u_omega)
            P_cf = eta_c * P1_sizing
            is_critical = P2_abs < P_cf
            calc_note = f"Flow is {'Critical' if is_critical else 'Subcritical'} (eta_c={eta_c:.3f})"
            v_0 = 1.0 / u_rho
            P0 = P1_sizing * 1000
            term = P0 / v_0
            G_si = eta_c * math.sqrt(term / u_omega) if is_critical else eta_c * math.sqrt( (P0/v_0) / u_omega ) 
            W_kg_s = W_base / 3600
            A_m2 = W_kg_s / (G_si * 0.9 * Kd * Kb * Kc)
            A_req = A_m2 * 1e6 
            if A_req < 0: A_req = 1.0
            formula_used = "A = W / (G_flux * Kd * Kb * Kc * 0.9)"

        api_orifices = {'B': 39, 'D': 71, 'E': 126, 'F': 198, 'G': 325, 'H': 506, 'J': 830, 'K': 1186, 'L': 1841, 'M': 2323, 'N': 2800, 'P': 4116, 'Q': 7129, 'R': 10323, 'T': 16774}
        sel_orf = "N/A"
        sel_area = 0
        sel_letter = ""
        for l, a in api_orifices.items():
            if a >= A_req:
                sel_orf = f"{l} ({a} mm²)"
                sel_area = a
                sel_letter = l
                break

        size_str = "Custom"
        if valve_standard == "API 526 (Flanged)":
            if sel_letter in api_526_sizes:
                in_s, out_s = api_526_sizes[sel_letter]
                size_str = f"{in_s} x {out_s}"
            else: size_str = "Check API Std"
        else:
            size_str = f"{sel_inlet_sz} x {sel_outlet_sz}"

        c1, c2, c3 = st.columns(3)
        c1.success(f"Required Area: **{A_req:.2f} mm²**")
        c2.metric("Selected Orifice", sel_orf)
        c3.metric("Valve Size", size_str)

        proj_d = {"Customer": customer, "Tag No": tag_no, "Description": desc, "Service": service_type}
        proc_d = {"Fluid": selected_fluid, "Required Flow": f"{raw_W} {unit_W}", "Set Pressure": f"{raw_P1} {unit_P1}", "Back Pressure": f"{raw_P2} {unit_P2}", "Relieving Temp": f"{raw_T1} {unit_T1}", "Overpressure": "10% Accumulation"}
        prop_d = {}
        if service_type == "Two-Phase": prop_d = {"Quality (x)": f"{input_quality}", "Omega (w)": f"{u_omega:.3f}", "Inlet Density": f"{u_rho:.1f} kg/m3"}
        else: prop_d = {"MW": f"{u_Mw:.2f}", "k (Cp/Cv)": f"{u_k:.3f}", "Z Factor": f"{u_Z:.3f}", "Specific Gravity": f"{u_SG:.3f}", "Viscosity": f"{u_visc:.3f} cP" if service_type=="Liquid" else "N/A"}
        prop_d.update({"Kd": f"{Kd}", "Kb": f"{Kb}", "Kc": f"{Kc}"})
        
        # --- ADDED C-to-F to Mechanical Data ---
        mech_d = {
            "Type": valve_standard, 
            "Valve Size": size_str, 
            "Orifice": sel_letter, 
            "Body Material": body_mat, 
            "Nozzle Material": nozzle_mat, 
            "Disc Material": disc_mat, 
            "Spring Material": spring_mat, 
            "Bellows": "Yes" if bellows else "No", 
            "Lever": lever_type, 
            "Inlet Conn": inlet_str, 
            "Outlet Conn": outlet_str,
            "Center to Face (Inlet)": f"{c_face_inlet} mm",
            "Center to Face (Outlet)": f"{c_face_outlet} mm"
        }
        
        res_d = {
            "Calculated Area": f"{A_req:.2f} mm²", 
            "Selected Area": f"{sel_area} mm² ({sel_letter})", 
            "Sizing Basis": "API 520 (Omega)" if service_type=="Two-Phase" else "API 520 Part I", 
            "Note": calc_note,
            "Formula Used": formula_used
        }

        pdf_data = create_datasheet(proj_d, proc_d, prop_d, mech_d, res_d)
        st.download_button("📥 Download SGM Datasheet", pdf_data, f"{tag_no}_Datasheet.pdf", "application/pdf")
        st.session_state.project_log.append({"Tag": tag_no, "Size": size_str, "Orifice": sel_letter, "Service": service_type})

    except Exception as e: st.error(f"Error: {e}")

st.markdown("---")
if st.session_state.project_log: st.dataframe(pd.DataFrame(st.session_state.project_log))
