import streamlit as st
import pandas as pd
from fpdf import FPDF
import math
import zipfile
import io
import os
import re

# --- 1. CONFIGURATION & IMPORTS ---
st.set_page_config(page_title="SGM Valve Sizing Pro", layout="wide", page_icon="🛡️")

try:
    import CoolProp.CoolProp as CP
    COOLPROP_AVAILABLE = True
except ImportError:
    COOLPROP_AVAILABLE = False

if 'project_log' not in st.session_state: st.session_state.project_log = []
if 'last_results' not in st.session_state: st.session_state.last_results = None

# ==========================================
# 2. DATABASES
# ==========================================

FLUID_DB = {
    "Air":          {"mw": 28.96, "k": 1.40},
    "Nitrogen":     {"mw": 28.01, "k": 1.40},
    "Oxygen":       {"mw": 32.00, "k": 1.40},
    "Argon":        {"mw": 39.95, "k": 1.67},
    "Natural Gas":  {"mw": 19.00, "k": 1.27},
    "CO2":          {"mw": 44.01, "k": 1.30},
    "Ammonia":      {"mw": 17.03, "k": 1.31},
    "Chlorine":     {"mw": 70.90, "k": 1.35},
    "LPG":          {"mw": 51.00, "k": 1.13},
    "Propane":      {"mw": 44.10, "k": 1.13},
    "Ethane":       {"mw": 30.07, "k": 1.19},
    "Water":        {"rho": 997.0, "visc": 1.0},
    "Oil (Generic)":{"rho": 850.0, "visc": 10.0},
    "LDO":          {"rho": 870.0, "visc": 3.5}
}

FLANGE_LIMITS = {
    "150#": 19.6, "300#": 51.1, "600#": 102.1, 
    "900#": 153.2, "1500#": 255.3, "2500#": 425.5
}

ORIFICE_DATA = {
    'B': {'area': 38.7, 'max_p': 420},   'C': {'area': 57.0, 'max_p': 420},
    'D': {'area': 71.0, 'max_p': 420},   'E': {'area': 126.5, 'max_p': 153},
    'F': {'area': 198.0, 'max_p': 51},   'G': {'area': 324.5, 'max_p': 19.6},
    'H': {'area': 506.0, 'max_p': 19.6}, 'J': {'area': 830.0, 'max_p': 19.6},
    'K': {'area': 1186.0, 'max_p': 19.6}, 'L': {'area': 1841.0, 'max_p': 19.6},
    'M': {'area': 2323.0, 'max_p': 19.6}, 'N': {'area': 2800.0, 'max_p': 19.6},
    'P': {'area': 4116.0, 'max_p': 19.6}, 'Q': {'area': 7129.0, 'max_p': 19.6},
    'R': {'area': 10323.0, 'max_p': 19.6},'T': {'area': 16774.0, 'max_p': 19.6}
}

API_526_SIZES = {'D': ('1"', '2"'), 'E': ('1"', '2"'), 'F': ('1.5"', '2"'), 'G': ('1.5"', '2.5"'), 'H': ('1.5"', '3"'), 'J': ('2"', '3"'), 'K': ('3"', '4"'), 'L': ('3"', '4"'), 'M': ('4"', '6"'), 'N': ('4"', '6"'), 'P': ('4"', '6"'), 'Q': ('6"', '8"'), 'R': ('6"', '8"'), 'T': ('8"', '10"')}

# --- HELPER: CLEAN TEXT FOR PDF ---
def clean_text(text):
    # Replaces common unicode chars with ASCII equivalents
    if not isinstance(text, str): return str(text)
    replacements = {
        "°": "deg", "²": "2", "³": "3", "±": "+/-", "≥": ">=", "≤": "<=",
        "⚠️": "Warning:", "🚨": "Alert:", "❌": "Error:", "🛡️": "", "🚀": "",
        "📊": "", "📦": "", "📥": "", "⬇️": ""
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    # Remove any other non-latin-1 characters
    return text.encode('latin-1', 'ignore').decode('latin-1')

# --- CSV READER ---
def get_spring_from_file(file_name, orifice, set_pressure):
    if not os.path.exists(file_name): return f"Err: File {file_name} missing", 0, 0
    try:
        df = pd.read_csv(file_name)
        df.columns = [str(c).strip().upper() for c in df.columns]
        if orifice not in df.columns: return f"Err: Orifice {orifice} not in CSV", 0, 0
        for index, row in df.iterrows():
            raw_val = str(row[orifice])
            match = re.search(r"(\d+\.?\d*)\s*[-–to]+\s*(\d+\.?\d*)", raw_val)
            if match:
                min_p = float(match.group(1))
                max_p = float(match.group(2))
                if min_p <= set_pressure <= max_p:
                    return str(row.iloc[0]), min_p, max_p
        return "Out of Spring Range", 0, 0
    except Exception as e: return f"CSV Error: {str(e)}", 0, 0

# ==========================================
# 3. PDF GENERATOR (Fixed Encoding)
# ==========================================
class PDF(FPDF):
    def header(self):
        try: self.image('logo.png', 10, 8, 33) 
        except: pass 
        self.set_y(10); self.set_font('Arial', 'B', 16); self.cell(0, 10, 'Safety Valve Datasheet', 0, 1, 'C')
        self.set_font('Arial', 'B', 12); self.set_text_color(0, 51, 102); self.cell(0, 8, 'SGM Valves and System Pvt Ltd', 0, 1, 'C')
        self.set_text_color(0, 0, 0); self.ln(5); self.set_line_width(0.5); self.line(10, 32, 200, 32); self.ln(5)
    def footer(self):
        self.set_y(-15); self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by SGM Valves Sizing Tool', 0, 0, 'C')

def create_datasheet(proj, proc, fluid, mech, res, safety):
    pdf = PDF(); pdf.add_page()
    
    def print_section(title, data_dict):
        # Clean title
        title = clean_text(title)
        pdf.set_font("Arial", 'B', 11); pdf.set_fill_color(230, 230, 230); pdf.cell(0, 7, title, 0, 1, 'L', fill=True); pdf.ln(1); pdf.set_font("Arial", size=9)
        keys = list(data_dict.keys())
        for i in range(0, len(keys), 2):
            k1 = clean_text(keys[i]); v1 = clean_text(str(data_dict[keys[i]]))
            pdf.cell(45, 6, f"{k1}:", 0, 0); pdf.cell(50, 6, v1, 0, 0)
            if i + 1 < len(keys):
                k2 = clean_text(keys[i+1]); v2 = clean_text(str(data_dict[keys[i+1]]))
                pdf.cell(45, 6, f"{k2}:", 0, 0); pdf.cell(50, 6, v2, 0, 1)
            else: pdf.ln(6)
        pdf.ln(3)

    print_section("1. General Detail", proj)
    print_section("2. Process Conditions", proc)
    print_section("3. Fluid Properties & Coefficients", fluid)
    print_section("4. Mechanical Construction", mech)
    
    pdf.ln(2); pdf.set_fill_color(255, 255, 255); current_y = pdf.get_y(); pdf.rect(10, current_y, 190, 45, 'F'); pdf.set_xy(10, current_y)
    pdf.set_font("Arial", 'B', 11); pdf.set_fill_color(230, 230, 230); pdf.cell(190, 7, "5. Sizing & Selection Results", 0, 1, 'L', fill=True); pdf.set_font("Arial", size=9); pdf.ln(1)
    
    for k, v in res.items():
        k_clean = clean_text(k); v_clean = clean_text(str(v))
        pdf.set_x(10); pdf.cell(45, 6, f"{k_clean}:", 0, 0); pdf.cell(140, 6, v_clean, 0, 1)
        
    pdf.set_y(pdf.get_y() + 5)
    print_section("6. Safety & Force Calculations", safety)
    
    # Return as latin-1 encoded bytes string
    return pdf.output(dest='S').encode('latin-1', 'ignore') 

# ==========================================
# 4. APP UI
# ==========================================
st.sidebar.markdown("## ⚙️ Sizing Inputs")
st.sidebar.header("1. General Detail")
customer = st.sidebar.text_input("Customer Name", "SGM Client")
tag_no = st.sidebar.text_input("Tag Number", "PSV-1001")
offer_no = st.sidebar.text_input("Offer No", "OFF-001")
enquiry_no = st.sidebar.text_input("Enquiry No", "ENQ-001")
desc = st.sidebar.text_input("Description", "Separator Relief")

st.sidebar.markdown("---")
# --- 2. Fluid Selection ---
st.sidebar.header("2. Fluid Selection")
service_type = st.sidebar.selectbox("Service Type", ["Gas/Vapor", "Liquid", "Steam", "Two-Phase"])

gas_list = ["Custom", "Air", "Nitrogen", "Oxygen", "Argon", "Natural Gas", "CO2", "Ammonia", "Chlorine", "LPG", "Propane", "Ethane"]
liq_list = ["Custom", "Water", "Oil (Generic)", "LDO"]

if service_type == "Gas/Vapor": fluids = gas_list
elif service_type == "Liquid": fluids = liq_list
else: fluids = ["Custom"]

selected_fluid = st.sidebar.selectbox("Select Fluid", fluids)

st.sidebar.markdown("---")
# --- 3. Process ---
st.sidebar.header("3. Process Conditions")
raw_W = st.sidebar.number_input("Required Flow Rate", value=1000.0)
unit_W = st.sidebar.selectbox("Flow Unit", ["kg/hr", "lb/hr", "Nm3/hr", "SCFM", "LPM"], key="u_flow")
c1, c2 = st.sidebar.columns(2)
raw_P1 = c1.number_input("Set Pressure", value=15.0)
unit_P1 = c2.selectbox("Unit", ["barg", "psig", "kg/cm2g"], key="u_p1")
overpressure_opt = st.sidebar.selectbox("Overpressure", ["10% Accumulation", "16% Accumulation", "21% Fire Case"])
op_mult = 1.10
if "16%" in overpressure_opt: op_mult = 1.16
elif "21%" in overpressure_opt: op_mult = 1.21
raw_BP_const = st.sidebar.number_input("Constant Back Pressure", value=0.0)
raw_BP_var = st.sidebar.number_input("Variable Back Pressure", value=0.0)
total_bp = raw_BP_const + raw_BP_var
raw_T1 = st.sidebar.number_input("Temperature", value=45.0)
unit_T1 = st.sidebar.selectbox("Unit", ["°C", "°F"], key="u_t1")
vapor_pressure_barg = 0.0
if service_type == "Liquid":
    st.sidebar.markdown("---")
    vapor_pressure_barg = st.sidebar.number_input("Vapor Pressure (barg)", value=0.02)

st.sidebar.markdown("---")
# Properties
st.sidebar.markdown("**Fluid Properties**")
def_mw = 28.96; def_k = 1.4; def_z = 0.95; def_rho = 997.0; def_visc = 1.0

if selected_fluid in FLUID_DB:
    props = FLUID_DB[selected_fluid]
    if "mw" in props: def_mw = props["mw"]
    if "k" in props: def_k = props["k"]
    if "rho" in props: def_rho = props["rho"]
    if "visc" in props: def_visc = props["visc"]

u_Mw = def_mw; u_k = def_k; u_Z = def_z; u_rho = def_rho; u_visc = def_visc

if service_type == "Gas/Vapor":
    u_Mw = st.sidebar.number_input("MW", value=float(def_mw))
    u_k = st.sidebar.number_input("k (Cp/Cv)", value=float(def_k))
    u_Z = st.sidebar.number_input("Z Factor", value=float(def_z))
elif service_type == "Liquid":
    u_rho = st.sidebar.number_input("Density (kg/m3)", value=float(def_rho))
    u_visc = st.sidebar.number_input("Viscosity (cP)", value=float(def_visc))

with st.sidebar.expander("4. Coefficients (Kd, Kb, Kc)"):
    Kd = st.number_input("Kd (Discharge)", value=0.975 if service_type!="Liquid" else 0.65)
    Kb = st.number_input("Kb (Back Pres)", value=1.0)
    Kc = st.number_input("Kc (Rupture Disc)", value=1.0)

st.sidebar.markdown("---")
# --- 5. Mechanical ---
st.sidebar.header("5. Mechanical Construction")
valve_standard = st.sidebar.radio("Select Valve Standard", ["API 526 (Flanged)", "Non-API / Compact (Threaded)"])
c_m1, c_m2 = st.sidebar.columns(2)
body_mat = c_m1.selectbox("Body Material", ["A216 Gr WCB", "SS316", "SS304"])
nozzle_mat = c_m2.selectbox("Nozzle Material", ["SS316", "SS304", "Monel"])
c_m3, c_m4 = st.sidebar.columns(2)
disc_mat = c_m3.selectbox("Disc Material", ["SS316", "SS304"])
spring_mat = c_m4.selectbox("Spring Material", ["Spring Steel", "SS316", "Inconel X750"])

st.sidebar.subheader("End Connections")
P_set_bar = raw_P1
if unit_P1 == "psig": P_set_bar = raw_P1 / 14.5
elif unit_P1 == "kg/cm2g": P_set_bar = raw_P1 * 0.98

conn_str = ""; manual_dim_in = 0; manual_dim_out = 0
if valve_standard == "API 526 (Flanged)":
    c_conn1, c_conn2 = st.sidebar.columns(2)
    inlet_rating = c_conn1.selectbox("Inlet Rating", ["150#", "300#", "600#", "900#", "1500#", "2500#"], index=1)
    limit = FLANGE_LIMITS.get(inlet_rating, 20)
    if P_set_bar > limit: st.sidebar.error(f"🚨 Set P ({P_set_bar:.1f} bar) exceeds {inlet_rating} limit!")
    outlet_rating = c_conn2.selectbox("Outlet Rating", ["150#", "300#"], index=0)
    conn_str = f"{inlet_rating} x {outlet_rating} RF"
else:
    c_sz1, c_sz2 = st.sidebar.columns(2)
    in_sz = c_sz1.selectbox("Inlet Size", ["1/2\"", "3/4\"", "1\"", "1-1/2\"", "2\""])
    out_sz = c_sz2.selectbox("Outlet Size", ["1/2\"", "3/4\"", "1\"", "1-1/2\"", "2\""])
    conn_type = st.sidebar.selectbox("Connection Type", ["NPT (Male x Female)", "NPT (Female x Female)", "BSP"])
    conn_str = f"{in_sz} x {out_sz} {conn_type.split(' ')[0]}"
    st.sidebar.markdown("**Dimensions (Manual)**")
    c_dim1, c_dim2 = st.sidebar.columns(2)
    manual_dim_in = c_dim1.number_input("C-to-Face Inlet (mm)", 0)
    manual_dim_out = c_dim2.number_input("C-to-Face Outlet (mm)", 0)
lever_type = st.sidebar.selectbox("Lever Type", ["None", "Packed Lever", "Open Lever"])
bellows_req = st.sidebar.checkbox("Bellows Required?", False)

# ==========================================
# 5. EXECUTION & LOGIC
# ==========================================
st.title("🛡️ SGM Valves - Sizing Pro")
st.markdown("### 📊 Sizing Dashboard")

if st.button("🚀 Calculate & Generate Datasheet"):
    # Calculation Logic
    W_base = raw_W 
    if unit_W == "lb/hr": W_base = raw_W * 0.453
    elif unit_W == "Nm3/hr": W_base = (raw_W / 22.414) * u_Mw
    T_K = raw_T1 + 273.15 if unit_T1 == "°C" else (raw_T1 - 32)*5/9 + 273.15
    P1_sizing_bar = (P_set_bar * op_mult) + 1.013
    req_area = 0.0; formula_used = ""
    
    if service_type == "Gas/Vapor":
        C = 520 * math.sqrt(u_k * ((2/(u_k+1))**((u_k+1)/(u_k-1)))) 
        term = math.sqrt((T_K * u_Z) / u_Mw)
        P1_kpa = P1_sizing_bar * 100
        req_area = (W_base * term * 13160) / (C * Kd * P1_kpa * Kb * Kc)
        formula_used = "A = (W * sqrt(T*Z*M)) / (C * Kd * P1 * Kb * Kc)"
    elif service_type == "Liquid":
        Q_m3h = W_base / u_rho; Q_gpm = Q_m3h * 4.403
        dP_bar = (P_set_bar * op_mult) - total_bp
        if dP_bar <= 0: st.error("Back Pres > Set Pres!"); st.stop()
        dP_psi = dP_bar * 14.5; G_liq = u_rho / 1000.0
        req_area_in2 = (Q_gpm * math.sqrt(G_liq)) / (38 * Kd * math.sqrt(dP_psi))
        req_area = req_area_in2 * 645.16
        formula_used = "A = (Q_gpm * sqrt(G)) / (38 * Kd * sqrt(dP))"

    # Select Orifice
    sel_orf = "N/A"; sel_area = 0
    valid_orifices = ORIFICE_DATA if valve_standard == "Non-API / Compact (Threaded)" else {k:v for k,v in ORIFICE_DATA.items() if k in API_526_SIZES}
    for l, data in valid_orifices.items():
        if data['area'] >= req_area and P_set_bar <= data['max_p']:
            sel_orf = l; sel_area = data['area']; break
    if sel_orf == "N/A": st.error("❌ No suitable orifice found."); st.stop()

    # Get Spring from CSV
    target_file = "spring_api.csv" if valve_standard == "API 526 (Flanged)" else "spring_non_api.csv"
    res_code, res_min, res_max = get_spring_from_file(target_file, sel_orf, P_set_bar)
    if res_code.startswith("Err") or res_code.startswith("Out"): spring_display = f"{res_code}"
    else: spring_display = f"{res_code} ({res_min}-{res_max} bar)"
    
    spring_force = (P_set_bar * 0.1) * sel_area
    
    # Safety Data
    W_kgs = W_base / 3600.0; react_force = 0.0; noise_msg = "Safe"
    if service_type == "Gas/Vapor":
        react_force = 1.29 * W_kgs * math.sqrt((u_k * T_K)/((u_k+1)*u_Mw))
        try: noise_msg = f"{12 + (17 * math.log10(W_kgs)) + (50 * math.log10(P_set_bar)):.1f} dBA"
        except: pass
    elif service_type == "Liquid":
        est_A_out = (sel_area * 6) / 1e6; react_force = (W_kgs**2) / (u_rho * est_A_out)
        if total_bp < vapor_pressure_barg: noise_msg = "!! FLASHING !!"
        elif (P_set_bar - total_bp) > 0.6*(P_set_bar - vapor_pressure_barg): noise_msg = "CAVITATION RISK"

    # Save
    res_pack = {"req_area": req_area, "sel_orf": sel_orf, "sel_area": sel_area, "conn_str": conn_str, "spring_display": spring_display}
    proj_d = {"Customer": customer, "Tag No": tag_no, "Offer No": offer_no, "Enquiry No": enquiry_no, "Description": desc, "Service": service_type}
    proc_d = {"Fluid": selected_fluid, "Set Pressure": f"{raw_P1} {unit_P1}", "Relieving Temp": f"{raw_T1} {unit_T1}", "Required Flow": f"{raw_W} {unit_W}", "Overpressure": overpressure_opt}
    fluid_d = {"Kd": Kd, "MW": u_Mw, "k": u_k, "Z": u_Z, "SG": f"{(u_rho/1000):.3f}" if service_type=="Liquid" else f"{(u_Mw/28.96):.3f}"}
    mech_d = {"Type": valve_standard, "Orifice": sel_orf, "Valve Size": conn_str, "Body": body_mat, "Trim": nozzle_mat, "Spring": spring_mat, "Lever": lever_type}
    res_d = {"Calculated Area": f"{req_area:.2f} mm2", "Selected Area": f"{sel_area} mm2", "Formula": formula_used}
    safe_d = {"Spring Model": spring_display, "Spring Load": f"{spring_force:.2f} N", "React Force": f"{react_force:.2f} N", "Noise/State": noise_msg}
    
    pdf_bytes = create_datasheet(proj_d, proc_d, fluid_d, mech_d, res_d, safe_d)
    st.session_state.last_results = res_pack
    st.session_state.project_log.append({"Tag": tag_no, "Size": conn_str, "Orifice": sel_orf, "PDF": pdf_bytes})

if st.session_state.last_results:
    r = st.session_state.last_results
    c1, c2, c3 = st.columns(3)
    c1.success(f"Rated Capacity: **{raw_W} {unit_W}**")
    c2.metric("Orifice / Spring", f"{r['sel_orf']} / {r['spring_display']}")
    c3.metric("Valve Size", r['conn_str'])
    st.download_button("📥 Download Datasheet", st.session_state.project_log[-1]['PDF'], f"{tag_no}.pdf", "application/pdf")

st.markdown("---")
if st.session_state.project_log:
    df = pd.DataFrame(st.session_state.project_log).drop(columns=["PDF"])
    st.table(df)
    if st.button("📦 Download Bundle"):
        zip_buffer = io.BytesIO()
        with zipfile.ZipFile(zip_buffer, "w") as zf:
            for item in st.session_state.project_log: zf.writestr(f"{item['Tag']}.pdf", item['PDF'])
        st.download_button("⬇️ Download ZIP", zip_buffer.getvalue(), "Project.zip", "application/zip")
